spring.datasource.url=jdbc:postgresql://localhost:5432/eldercare_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=mistral:latest
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true